### ISSUE TITLE
Automatically deploy every branch

### ISSUE THREAD

**Issue by oferb** [hasadna/sensory-interface#26]
This is a task to ease development.

Right now we have 2 hostings - one for `dev` and one for `prod`. Ideally, we would host every branch.
Since we're only front-end, that's much easier since it doesn't require any server.

Proposed solution:
A small server that does git pull every second, and serves the different branches as subdomains. For example, master.sensoryinterface.com would show the website on the master branch. branch3.sensoryinterface.com would show the contents on branch3. Once that's set up, it doesn't require anything from the developers, they develop just the same, it just shows up automatically on that url.

**Comment by S0AndS0** [comment]
There shouldn't be a reason to pull for updates; GitHub Web Hooks, GitHub Actions, and TravisCI all have the ability to react to repository changes...


- https://developer.github.com/v3/repos/hooks/

- https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-a-docker-container-action

- https://travis-ci.com/


... I tested Web Hooks many moons ago, but found it was pretty good when running a private server. TravisCI is by far my favorite because it means that this project isn't beholden to GitHub beyond hosting of source and examples, plus reproducing development environments are well documented; TravisCI is what I would call a _mature_ service for this use case. And while I've written stuff for GH-Actions in the past, it was a bit more setup than either of the other two options so far listed.

**Comment by oferb** [comment]
Ok. Say I want to view the hosted project at <branch>. How would I do that?

**Comment by S0AndS0** [comment]
There are few ways to view changes


- GitHub pages, update a submodule within a `gh-pages` branch to point at the `master` branch of either this repository or one of it's forks.

- GitHub Web Hooks, set a web hook to notify a server that it's time to pull in updates.

- GitHub Actions, set up authorization to a server or repository and have it trigger on `push` events for this project or one of it's forks.

- Travis-CI, write a configuration file for authorization to a server or repository and have it trigger on `push` events for this project or one of it's forks.

Both GitHub Actions and Travis-CI are services that are kinda intended for contentious integration and/or deployment. Each are able to spin up a VM (Virtual Machine), download the source code, run scripts, and then if needed upload results anywhere authorized.

Not only does this avoid hammering GitHub servers every few minuets to hours to check for updates, this kind of setup ensures that there's some kind of _road-map_ for reproducing deployment setup.

**Comment by S0AndS0** [comment]
Here's a quick example of utilizing Travis CI for TypeScript builds to the `build/` directory, which happens to be a submodule on the `master` branch, and then pushing results to some remote...


**`.travis.yml`**


```YAML
language: node_js
node_js:
  - 13

branches:
  only:
    - dev
  except:
    - gh-pages
    - master

cache: npm

jobs:
  fast_finish: true

before_install:
  - git submodule update --init --merge --recursive --remote
  - npm install

install:
  - npm run build

# before_script:
#   - npm run special_before_script_stuff_maybe

script:
  - printf 'script is similar to "try" part of "try"/"catch"/"finally" statements\n'
  # - npm run tests


after_failure:
  - printf 'after_failure asks - Where did %s go wrong?\n' "${USER}"
  - printf 'Kinda like "catch", with "try"/"catch"/"finally" statements\n'

after_success:
  - printf 'after_success states it all seems okay?\n'
  - printf 'for "try"/"catch"/"finally" statements, kinda like "else" nothing bad\n'
  - printf 'happened; i.e. a good place for uploading, pushing, etc. to remote\n'
  # - eval "$(ssh-agent -s)"           # start the ssh agent
  # - cd build
  # - git commit -m ':robot: Travis CI tested and pushed\n'
  # - git remote add deploy DEPLOY_REPO_URI_GOES_HERE 2>&1
  # - git push --force deploy master 2>&1


after_script:
  - printf 'after_script is bit like "finally" part in "try"/"catch" statement\n'
  - printf 'Good place for a toast maybe?\n'
```


... there are a good things about each;


- If I remember correctly GitHub Actions could auto-push, to the same repository of a given Action, without the need of secrets being saved as there are some kind of environment variables to facilitate such things.

- Web Hooks are fantastic for VPS (Virtual Private Server) deployments, I tested'em many moons ago and not for very long, but it was nifty having a server get notified that it was time to pull. Better still is that for simple setups the VPS would be doing a pull only.

- GitHub Pages combined with Dependabot is possibly the simplest to setup, but requires some human input for accepting merge requests; some may consider it a good thing.

- Travis CI can deploy just about anywhere that you're authorized for, the service is very Open Source friendly, and the configuration files can be readable enough for anyone to step through things at a terminal.


## Attribution


- [StackOverflow -- Using secret API keys on Travis-CI](https://stackoverflow.com/questions/9338428)

- [StackOverflow -- Unable to push deployment from Travis-CI to CloudControl](https://stackoverflow.com/questions/23942390)

- [Travis-CI -- JavaScript with NodeJS](https://docs.travis-ci.com/user/languages/javascript-with-nodejs/)

- [Travis-CI -- Custom Deployment](https://docs.travis-ci.com/user/deployment/custom/)

- [Travis-CI -- Best Practices in Securing Your Data](https://docs.travis-ci.com/user/best-practices-security/)

- [Travis-CI -- Environment Variables](https://docs.travis-ci.com/user/environment-variables/)
